# Generated by Django 3.0.8 on 2020-07-14 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='djangoClasses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=60)),
                ('course', models.IntegerFieldField(default='')),
                ('instructor', models.TextField(blank=True, default='', max_length=60)),
                ('duration', models.FloatField(default=0)),
            ],
        ),
    ]
