# Generated by Django 3.0.8 on 2020-07-14 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classApp', '0002_auto_20200713_2109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='djangoclasses',
            name='course',
            field=models.IntegerField(default='', max_length=60),
        ),
        migrations.AlterField(
            model_name='djangoclasses',
            name='duration',
            field=models.FloatField(default=0),
        ),
    ]
